[package]
name = "project_exe"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
# Internal dependencies
project_lib.workspace = true

# External dependencies
parking_lot.workspace = true
